name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.9]
        # os: [macos-latest, ubuntu-latest, windows-2019]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge

    - name: check python installation
      run: |
        conda --version
        which python
        python -V

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install the chunky packages with conda:
        conda install --yes \
          ecos \
          scs \
          osqp \
          coin-or-cbc
        pip install -e .[test]
        pip list

    - name: Test with pytest
      run: |
        pytest --verbose --color=yes
